services:
  app:
    image: app:latest
    build: 
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./app/:/code/app/
    env_file:
      - .env
    ports:
      - 8000:8000
    platform: linux/amd64

  db:
    image: postgres:13
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/
      - POSTGRES_PASSWORD=${DB_PASS?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    ports:
      - 5432:5432

volumes:
  db: