version: "3.8"
services:
  backend:
    build:
      context: .
    image: fastapi-boilerplate-backend:${VERSION}
    container_name: fastapi-boilerplate-backend
    platform: linux/amd64
    volumes:
      - ./app/:/code/app/
    environment:
      - DB_HOST=${DB_HOST?Variable not set}
      - DB_PORT=${DB_PORT?Variable not set}
    ports:
      - 8000:8000

  db:
    image: postgres:15.0
    container_name: fastapi-boilerplate-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASS?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    ports:
      - 5432:5432
