# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction

      - name: Formatting
        run: poetry run black --check app
      - name: Linting
        run: poetry run ruff check app --fix
      - name: Static Type Checking
        run: poetry run mypy app

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: python -m pip install isort
      - name: isort
        # Pinned to v2.0.0.
        uses: isort/isort-action@v1.1.0
        with:
          run: |
            isort . --profile=black --multi_line_output=24
